### ISSUE TITLE
Recent transactions -> Incorrect pincode

### ISSUE THREAD

**Issue by antonym8** [antonym8/Grouppal-Franchise#10]
Recent transactions pincode is not purchased by the user

![Screenshot_20240125_144726](https://github.com/antonym8/Grouppal-Franchise/assets/142376069/9d207310-6738-4c6a-b793-2afc080c6936)
![Screenshot_20240125_151205](https://github.com/antonym8/Grouppal-Franchise/assets/142376069/0870e3d2-18fa-4f21-8b50-8847af0d3843)

**Comment by m8dharma** [comment]
fixed- Dummy data
